export const AUTH_LOGOUT = 'AUTH_LOGOUT'

// users

export const USERS_GET_ALL_REQUEST = 'USERS_GET_ALL_REQUEST'
export const USERS_GET_ALL_SUCCESS = 'USERS_GET_ALL_SUCCESS'
export const USERS_GET_ALL_FAILURE = 'USERS_GET_ALL_FAILURE'

export const PHOTO_TAKEN = 'PHOTO_TAKEN'
export const REGISTERING_DEVICE = 'REGISTERING_DEVICE'
export const REGISTERED_DEVICE = 'REGISTERED_DEVICE'
export const UPDATING_STATUS = 'UPDATING_STATUS'
export const UPDATED_STATUS = 'UPDATED_STATUS'
export const UPLOADING_PHOTO = 'UPLOADING_PHOTO'
export const UPLOADED_PHOTO = 'UPLOADED_PHOTO'
